CREATE TABLE IF NOT EXISTS bpm_finished_process (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_instance_id VARCHAR(255) NOT NULL,
    finished_by VARCHAR(255),
    status VARCHAR(255),
    message VARCHAR(4000),
    finished_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bpm_finished_process_instance_id
    ON bpm_finished_process (process_instance_id);

CREATE INDEX IF NOT EXISTS idx_bpm_finished_process_finished_at
    ON bpm_finished_process (finished_at);

CREATE INDEX IF NOT EXISTS idx_bpm_finished_process_finished_by
    ON bpm_finished_process (finished_by);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, role),
    CONSTRAINT fk_user_roles_user_id
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS revoked_jwt (
    jti VARCHAR(64) PRIMARY KEY,
    user_id BIGINT NULL,
    revoked_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_revoked_jwt_expires_at
    ON revoked_jwt (expires_at);

CREATE TABLE IF NOT EXISTS qbpmcockpit_user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    base_url VARCHAR(2048)
);

CREATE TABLE IF NOT EXISTS qbpmplayer_user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    base_url VARCHAR(2048),
    context VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS resolver_access_user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    realm VARCHAR(255),
    client_id VARCHAR(255),
    access_user VARCHAR(255),
    url VARCHAR(2048)
);

CREATE TABLE IF NOT EXISTS resolver_token_user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    token VARCHAR(4000)
);
